config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root 'users#show'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end


  # Example resource route (maps HTTP verbs to controller actions automatically):
    resources :events
  resources :invites

end

app/models/event.rb
class Event < ActiveRecord::Base

  	belongs_to :creator,     :class_name  => "User"

  	has_many   :invites,     :foreign_key => :attended_event_id
  	has_many   :attendees,   through:        :invites


    	# def self.upcoming
    	# 	Event.where('date >= ?', DateTime.now)
    	# end
      #
    	# def self.past
    	# 	Event.where('date < ?', DateTime.now)
    	# end

	scope			 :upcoming, -> { where('date >= ?', DateTime.now).order('Date ASC') }
	scope      :past,     -> { where('date < ?', DateTime.now).order('Date DESC') }


end

app/models/invite.rb
class Invite < ActiveRecord::Base

  	belongs_to :attendee,       :class_name => "User"
  	belongs_to :attended_event, :class_name => "Event"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  	has_many :created_events,  :foreign_key => "creator_id", :class_name => "Event"

  	has_many :invites,         :foreign_key => :attendee_id
  	has_many :attended_events, through:        :invites


    	# def upcoming_events
    	# 	self.attended_events.where('date >= ?', DateTime.now)
    	# end
      #
    	# def previous_events
    	# 	self.attended_events.where('date < ?', DateTime.now)
    	# end


      scope			 :upcoming, -> { where('date >= ?', DateTime.now).order('Date ASC') }
      scope      :past,     -> { where('date < ?', DateTime.now).order('Date DESC') }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render'new'
    end
  end

  def show
    @event=Event.find(params[:id])
    @creator = @event.creator

    # let's try this
    # @attendees = @event.attendee
		@attendees = @event.attendees.all
      # @events = @user.events

  end

  def index
    @events=Event.all


		@upcoming = Event.upcoming
		@past     = Event.past
  end

  private

  def event_params
    params.require(:event).permit(:name, :date)
    # params.require(:event).permit(:name, :date, :attendee)
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

	def create
		@event = Event.find(params[:invite][:attended_event_id])
		current_user.invites.create(attended_event_id: @event.id)
		redirect_to @event
	end

	def destroy
		@event = Event.find(params[:invite][:attended_event_id])
		current_user.invites.destroy(attended_event_id: @event.id)
		redirect_to @event
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!


  def show
    @user=current_user
    # @events = Event.(current_user).order("created_at DESC")

  # this line works to show all the user created events
  @created_events = @user.created_events



    @attended_events = @user.attended_events

		@upcoming_events = @user.attended_events.upcoming
		@prev_events     = @user.attended_events.past
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<!-- <% @events.each do |event| %>


<p><%= event.name %> by <%= event.creator.email %> </p>

<% end %> -->


<h2>Upcoming</h2>
<% @upcoming.each do |upcoming_event| %>
<h3> <%= upcoming_event.name %> </h3>
<h4> by <%= upcoming_event.creator.email %></h3>
	<h4> <%= upcoming_event.date.strftime("%B %d, %Y") %> at <%= upcoming_event.date.strftime("%I:%M %p") %> </h4>
<h5> <%= upcoming_event.attendees.count %> attending. </h5>
<% end %>

<h2>Past</h2>
<% @past.each do |past_event| %>
<h3> <%= past_event.name %> </h3>
<h4> by <%= past_event.creator.email %></h4>
<h4> <%= past_event.date.strftime("%B %d, %Y") %> at <%= past_event.date.strftime("%I:%M %p") %> </h4>
<h5> <%= past_event.attendees.count %> attended. </h5>
<% end %>

app/views/events/new.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :name %>
    <%= f.input :date %>
  <%= f.button :submit %>
<% end %>

app/views/events/show.html.erb
<% unless @event.attendees.include?(current_user) %>
	<%= form_for(current_user.invites.build(attended_event_id: @event.id)) do |f| %>
		  <%= f.hidden_field :attended_event_id, :value => @event.id %>
			<%= f.submit "Attend Event" %>
	<% end %>
<% end %>


<h2> Event: <%= @event.name %> </h2>

<h2> Created by: <%= @creator.email %> </h2>

<h2> Attendees </h2>

<% @attendees.each do |attendee| %>

<p><%= @event.name %> has <%= attendee.email %> attending </p>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? -%>
	<ul>
		<li><%= link_to "#{current_user.email}", edit_user_registration_path %></li>
		<li><%= link_to "My Events", root_path %></li>
		<li><%= link_to "All Events", events_path %></li>
		<li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
	</ul>
<% else %>
	<ul>
		<li><%= link_to "Sign In", new_user_session_path %></li>
		<li><%= link_to "Sign Up", new_user_registration_path %></li>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<%= render 'layouts/header' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h1> Welcome! </h1>
 <h3> <%= @user.email %> </h3>


<h4> Created Events </h4>
 <ul>
<% @created_events.each do |created_event| %>
<li>	<%= created_event.name %> </li>
<% end %>
</ul>


<h4> Upcoming Events </h4>
<ul>
<% @upcoming_events.each do |upcoming_event| %>
<li> <%= upcoming_event.name %> </li>
<% end %>
</ul>

<h4> Previous Events </h4>
<ul>
<% @prev_events.each do |prev_event| %>
<li> <%= prev_event.name %> </li>
<% end %>
</ul>